env:
  browser: true
  es6: true
  mocha: true
  node: true
extends:
  - eslint:recommended
  - prettier
parserOptions:
  ecmaVersion: 9
  sourceType: module
plugins:
  - prettier
rules:
  no-console: 0
  no-var: error
  prefer-const: error
  prettier/prettier: error
  quotes:
    - error
    - single
    - avoidEscape: true
