language: node_js
node_js:
- '11'
- '12'
- '13'
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  edge: true
  email: curt.tudor@netfoundry.io
  api_key:
    secure: LnRU9R73jsGbG3Blij/GH4HGNFXp6taT+Y6VqtgQSP9si08NTqmgOFPF5JhVpPJSBkjQVeRV2Pewb6FsHDFEtiRfZt9IUJtdmXEcq1/5vzOQ2m4GhmREJZBaAf7qyx9552+cMMzW/Bha94Dt3B7Y9n8hQZlURm2iQtWEExntTjQEEX5KT5C3ON3To9KGdJkkhd8VjizEiRnPu1T+CSlbSj7Tnc/U3KmkXmy6NgN9QpLcKLm/urCU1dOY32DuLJHh00CdWvDaCezF+rE9LLmuOt76zClB+967kS0i0+O8YQSSg/aVaimfZtkzmTFwchc8m8cZzq0Sb1HdarBGBxcPIJRayXvSRBydAAJolwyNDrPmuJsC4BedocvyMafKSyQY9rpxaghAIWQ9hobb3kBxpf92wAkxMTNv1KphBZXB/Ilf8xND3cI4aqUmFbBatsjNoxiYMwJ/aQUQg8qK30DHo9pM8i3aMIU0cpMZSwI3jhGMri9er659N/9geCgY3xJXLXGVcrtR+IZGj70/lDGFmZ/MpXevhIQGtPqCISojxGCFcLDw01iAuE9kqYanXpXn+o747XvZua7Oq29zl+el81LOSyh2OAvdcmz4MsAbrGLWYzACBIGX3xcNPjPlVsN0z88WmALo7zf5UQ7ZDlsIkp7qIvb58IvBohC5tol9EB8=
  on:
    tags: true
    branch: master
