language: node_js
node_js:
- '12'
- '13'
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  edge: true
  email: curt.tudor@netfoundry.io
  api_key:
    secure: u9BzMSC2P7P/MwQxS6pHneEXSnVRUovzwjgiKEpT1pUvkqTNyUjfycdFVLuH98WKS9V5B+ipOolV1oon66ohl55Gc0I6C9uWtVPPOxNv3l2tq8NsDnO+9y1fZYfjInGxoeBua83HTb1GT4w7TaT2HxHMXqfYtISKlcwdTTFxDRZnnmq2CH/m2/HQM5lwnD1A8ptrP9CDfnnfb1IS06YgxBkT31sK5Z2m7zTBx/qNdCyIKDBVnZwzHE7COzUljrycgUAsLVdep3vs0UcaIB33Nyja+T3GKNagPQQUE47KYFEZ4omaFJJsF1JCwqxzZzjqH2uGe9xtJfDbAfgkouV2hc4EcdIsgy1Bmj1fSLS3U+HHRviouhNnSKXD8t4X/xiactcyydBrFiA+25B9lpftCvQ8l/UP8fqz9Uo5iy4ZklnUq8OPhM/AhAhke86DHagi7LwEYRHMzd9d1Z61YgYqduMbe7MUmZZY9HPADFdnMOs48ZzEuQvyEaK0JHjXhhmuLHLIyYbn52QlAppEJ35iJJls+3h4PxtVTHjk3r8pNs50SMp7iHJObGL1drMCAosSq+f5r/cEa/KRgwHpv+OIs2aZtqiV2DlygB39aNWMTIx0l4YAhpgnNYgWEbi/6YqHE/uKm5Rh7ExoygZEhDa/IYl79iyroS/teYWi9KK4qso=
  on:
    tags: true
    branch: master
